/**
 * Akmey
 * Akmey is a keyserver for SSH public keys
 *
 * OpenAPI spec version: 0.0.1-r2
 * Contact: me@leonekmi.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DeleteResponse', 'model/EditResponse', 'model/FullKey'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DeleteResponse'), require('../model/EditResponse'), require('../model/FullKey'));
  } else {
    // Browser globals (root is window)
    if (!root.Akmey) {
      root.Akmey = {};
    }
    root.Akmey.KeysApi = factory(root.Akmey.ApiClient, root.Akmey.DeleteResponse, root.Akmey.EditResponse, root.Akmey.FullKey);
  }
}(this, function(ApiClient, DeleteResponse, EditResponse, FullKey) {
  'use strict';

  /**
   * Keys service.
   * @module api/KeysApi
   * @version 0.0.1-r2
   */

  /**
   * Constructs a new KeysApi. 
   * @alias module:api/KeysApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Fetch the key on Akmey
     * @param {String} key Content of key (w/o comment) to return
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/FullKey} and HTTP response
     */
    this.keyFetchPostWithHttpInfo = function(key) {
      var postBody = null;

      // verify the required parameter 'key' is set
      if (key === undefined || key === null) {
        throw new Error("Missing the required parameter 'key' when calling keyFetchPost");
      }


      var pathParams = {
      };
      var queryParams = {
        'key': key,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = FullKey;

      return this.apiClient.callApi(
        '/key/fetch', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch the key on Akmey
     * @param {String} key Content of key (w/o comment) to return
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/FullKey}
     */
    this.keyFetchPost = function(key) {
      return this.keyFetchPostWithHttpInfo(key)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Add a key
     * @param {String} key Content of key (w/o comment) to add
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EditResponse} and HTTP response
     */
    this.keysAddPostWithHttpInfo = function(key) {
      var postBody = null;

      // verify the required parameter 'key' is set
      if (key === undefined || key === null) {
        throw new Error("Missing the required parameter 'key' when calling keysAddPost");
      }


      var pathParams = {
      };
      var queryParams = {
        'key': key,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['akmey_auth', 'akmey_token'];
      var contentTypes = [];
      var accepts = [];
      var returnType = EditResponse;

      return this.apiClient.callApi(
        '/keys/add', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Add a key
     * @param {String} key Content of key (w/o comment) to add
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EditResponse}
     */
    this.keysAddPost = function(key) {
      return this.keysAddPostWithHttpInfo(key)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete key
     * @param {String} keyId ID of key to remove
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DeleteResponse} and HTTP response
     */
    this.keysKeyIdDeleteWithHttpInfo = function(keyId) {
      var postBody = null;

      // verify the required parameter 'keyId' is set
      if (keyId === undefined || keyId === null) {
        throw new Error("Missing the required parameter 'keyId' when calling keysKeyIdDelete");
      }


      var pathParams = {
        'keyId': keyId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['akmey_auth', 'akmey_token'];
      var contentTypes = [];
      var accepts = [];
      var returnType = DeleteResponse;

      return this.apiClient.callApi(
        '/keys/{keyId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete key
     * @param {String} keyId ID of key to remove
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DeleteResponse}
     */
    this.keysKeyIdDelete = function(keyId) {
      return this.keysKeyIdDeleteWithHttpInfo(keyId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a key by its ID
     * @param {String} keyId ID of key to return
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/FullKey} and HTTP response
     */
    this.keysKeyIdGetWithHttpInfo = function(keyId) {
      var postBody = null;

      // verify the required parameter 'keyId' is set
      if (keyId === undefined || keyId === null) {
        throw new Error("Missing the required parameter 'keyId' when calling keysKeyIdGet");
      }


      var pathParams = {
        'keyId': keyId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = FullKey;

      return this.apiClient.callApi(
        '/keys/{keyId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a key by its ID
     * @param {String} keyId ID of key to return
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/FullKey}
     */
    this.keysKeyIdGet = function(keyId) {
      return this.keysKeyIdGetWithHttpInfo(keyId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Edit your key comment
     * @param {String} keyId ID of key to edit
     * @param {String} comment Comment of the key
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EditResponse} and HTTP response
     */
    this.keysKeyIdPutWithHttpInfo = function(keyId, comment) {
      var postBody = null;

      // verify the required parameter 'keyId' is set
      if (keyId === undefined || keyId === null) {
        throw new Error("Missing the required parameter 'keyId' when calling keysKeyIdPut");
      }

      // verify the required parameter 'comment' is set
      if (comment === undefined || comment === null) {
        throw new Error("Missing the required parameter 'comment' when calling keysKeyIdPut");
      }


      var pathParams = {
        'keyId': keyId
      };
      var queryParams = {
        'comment': comment,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['akmey_auth', 'akmey_token'];
      var contentTypes = [];
      var accepts = [];
      var returnType = EditResponse;

      return this.apiClient.callApi(
        '/keys/{keyId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Edit your key comment
     * @param {String} keyId ID of key to edit
     * @param {String} comment Comment of the key
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EditResponse}
     */
    this.keysKeyIdPut = function(keyId, comment) {
      return this.keysKeyIdPutWithHttpInfo(keyId, comment)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
